version: '3.8'
services:
  db:
    image: postgres:14.5
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init_data/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=application